name: Deploy To EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} # EC2의 주소
          username: ${{ secrets.USERNAME }} # EC2 접속 ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # EC2의 Key 페어
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            cd /home/spring/deployTest
            git config --global --add safe.directory /home/spring/deployTest
            sudo git pull origin master
            sudo ./gradlew bootWar
            sudo fuser -k -n tcp 8080 
            nohup java -jar build/libs/*SNAPSHOT.war & cd
            
#            nohup java -jar build/libs/*SNAPSHOT.war > /dev/null 2>&1 &
#            sudo lsof -i:8080